"""``darth-infra init`` — first-run project creation.

This is the entry point for creating a brand-new darth-infra project. In
interactive mode it launches the Guided configuration editor in *creation*
mode: nothing is written to disk until the operator confirms creation in
Review. Non-interactive mode scaffolds directly from an existing config file
without launching Textual, which keeps automation and CI workflows unchanged.

Editing an *existing* project is the job of ``darth-infra tui`` (see
:mod:`darth_infra.cli.tui_cmd`); this command never opens an existing project
for document-preserving editing.
"""

from __future__ import annotations

from pathlib import Path

import click
from rich.console import Console

from ..config.loader import CONFIG_FILENAME, load_config
from .install_skill_cmd import install_skill_for_new_project
from .version_floor import apply_current_cli_version_floor, enforce_cli_version_floor

console = Console()

# Canonical starting point for a brand-new project. Creation mode edits this
# in-memory draft; the real project files are generated by the editor only after
# the operator confirms creation in Review, at which point the CLI version floor
# is stamped and the document is re-serialized canonically.
NEW_PROJECT_TEMPLATE = """\
[project]
name = "my-project"
aws_region = "us-east-1"
environments = ["prod"]

[[services]]
name = "web"
port = 8000
"""


@click.command("init")
@click.option(
    "-o",
    "--output",
    "output_dir",
    type=click.Path(path_type=Path),
    default=None,
    help="Output directory for the CloudFormation project. Defaults to the current directory.",
)
@click.option(
    "--non-interactive",
    is_flag=True,
    default=False,
    help="Skip the editor and scaffold directly from a config file.",
)
@click.option(
    "--no-skill",
    is_flag=True,
    default=False,
    help="Skip installing the darth-infra.toml authoring skill for coding agents.",
)
@click.option(
    "--config",
    "config_path",
    type=click.Path(exists=True, path_type=Path),
    default=None,
    help="Path to an existing darth-infra.toml (for non-interactive mode).",
)
def init_cmd(
    output_dir: Path | None,
    non_interactive: bool,
    no_skill: bool,
    config_path: Path | None,
) -> None:
    """Create a new darth-infra project and scaffold its CloudFormation output."""
    from ..scaffold.generator import generate_project

    if non_interactive:
        if config_path is None:
            raise click.UsageError("--config is required when using --non-interactive")
        config = load_config(config_path)
        enforce_cli_version_floor(config)
        apply_current_cli_version_floor(config)
        out = output_dir or Path.cwd()
        result = generate_project(config, out)
        console.print(f"[green]Project scaffolded at {result}[/green]")
        install_skill_for_new_project(out, skip=no_skill)
        return

    # Interactive first-run creation via the Guided editor. Creation mode holds
    # the new project as an in-memory draft and requires Review confirmation
    # before any files are written.
    from ..config.document import ProjectDocument
    from ..tui.editor import ConfigEditorApp

    out = output_dir or Path.cwd()
    document = ProjectDocument(out / CONFIG_FILENAME, NEW_PROJECT_TEMPLATE)
    app = ConfigEditorApp(document=document, mode="create", output_dir=out)
    app.run()
    install_skill_for_new_project(out, skip=no_skill)
